apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql

spec:
  serviceName: mysql

  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql

        image: {{ .Values.mysql.image }}

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}

        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.secret.password }}

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage

    spec:
      accessModes:
      - ReadWriteOnce

      resources:
        requests:
          storage: {{ .Values.mysql.storage }}